# Site settings
title: 'Carpe diem'  # Your Title
tagline: 'To be someone interesting'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
cameraurl: /pho/
fragmenturl: /fragment/

# Personal info
avatar: https://i.loli.net/2018/08/30/5b875faf4076e.png
email: nowhitestar@gmail.com
github: https://github.com/nowhitestar
weibo: https://weibo.com/liaoyuxing1001
music: https://music.163.com/#/user/home?id=46012777
twitter: https://twitter.com/LuiseLiao

# Logo setting
logocolor: '#000'
