# Site settings
title: 'Carpe diem'  # Your Title
tagline: 'To be someone interesting'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
cameraurl: /pho/
fragmenturl: /fragment/

# Personal info
avatar: https://p71vl47v1.bkt.clouddn.com/20180423152449110725325.png
email: nowhitestar@gmail.com
github: https://github.com/nowhitestar
weibo: https://weibo.com/liaoyuxing1001
music: https://music.163.com/#/user/home?id=46012777
twitter: https://twitter.com/LuiseLiao

index_image: https://p71vl47v1.bkt.clouddn.com/20180423152444798659053.jpg
index_word: 「 幸会，我是不白 」
# Logo setting
logocolor: '#000'
